# -*- coding: utf-8 -*-
"""Axial Heat Loss in Thermal Fluids.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSj4nBfgGVX6WLf5ivg0lVUXDcazpPzp
"""

import numpy as np
import matplotlib.pyplot as plt

rho = 850.0 #kg/m3
cp = 1200.0 #J/kg-K
mfr = 0.5 #kg/s

L = 10.0 #m
D = 0.2 #m
N = 21 #axial nodes (+1 to account for node zero)
NL = L/N #node length

A_cs = np.pi*(D/2)**2 #cross sectional area
A_surf = np.pi * D * (L / N) # Surface area per node
V_node = A_cs*NL #node volume
m_node = rho*V_node #node mass

h = 100.0 #W/m2-K, HEx coeff
T_inf = 250.0 # K
T_in = 300.0 # K

q_vol = 10e6 #W/m3
q_gen = q_vol*V_node

dt = 10 #s
t_total = 3600 #s
t = np.arange(0,t_total,dt)

Temp = np.ones(N)*T_in
Temp_point = []

for n in t:
  Temp_new = Temp.copy()

  for i in range(N):
    if i == 0:
      Temp_next = T_in
    else:
      Temp_next = Temp[i-1]

    q_flow = mfr * cp * (Temp_next - Temp[i])  # W, mCpdT
    q_conv = h * A_surf * (Temp[i]-T_inf) # W, convective HEx

    dTdt = (q_flow + q_gen - q_conv) / (m_node * cp) # energy balance solving for temp differential

    Temp_new[i] = Temp[i] + dTdt * dt

  Temp_new[0] = T_in
  Temp = Temp_new
  Temp_point.append(Temp.copy())


Temp_point = np.array(Temp_point)

final_temp = Temp_point[-1]
nodes = np.arange(N)
table = np.column_stack((nodes, final_temp))
print("Node | Temperature (K)")
print("----------------------")
for n, T in table:
    print(f"{int(n):4d} | {T:10.2f}")


plt.figure()
plt.ylim(0,3500)
plt.xlim(0,20)
plt.plot(Temp_point[-1])
plt.xlabel("Axial Node")
plt.ylabel("Temperature (K)")
plt.title("Axial Temperature Distribution")
plt.grid()

plt.show()